server:
  port: 8088
spring:
  application:
    name: application-center
info:
  name: @name@
  version: @project.version@
management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
    logfile:
      enabled: true
      external-file: ${logging.path}/server/server_error.log
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"