eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    healthcheck:
      enabled: true
    refresh:
      enable: true
    service-url:
      defaultZone: http://121.40.214.119:8088/eureka/
  server:
    enable-self-preservation: false
  instance:
    prefer-ip-address: true
spring:
  boot:
    admin:
      client:
        enabled: true
        url: http://121.40.214.119:8089
        username: admin
        password: admin
        auto-deregistration: true
        auto-registration: true
        instance:
          prefer-ip: true