server:
  port: 8088
spring:
  application:
    name: application-center
info:
  name: @name@
  version: @project.version@
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false