server:
  port: 8088
spring:
  application:
    name: application-center
info:
  name: @name@
  version: @project.version@
management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"